# Generated by Django 5.1.6 on 2026-04-04 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=32, unique=True, verbose_name='identifiant unique')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('age', models.PositiveSmallIntegerField(verbose_name='âge')),
                ('medical_info', models.TextField(blank=True, verbose_name='informations médicales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'nurse'}, on_delete=django.db.models.deletion.PROTECT, related_name='patients_created', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par (infirmier·e)')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
